### ISSUE TITLE
Increase the width of version column in output format

### ISSUE THREAD

**Issue by bmanikm** [rebro-msft/psget-prerelease#3]
- This is applicable to all PowerShellGet output formats with Version property.

PS C:\WINDOWS\system32> find-module -Repository int -name RebroTestPackage -AllVersions -AllowPrerelease

Version    Name                                Repository           Description
-------    ----                                ----------           -----------
3.0.0-a... RebroTestPackage                    int                  Test Package for prerelease versions.
2.0.0      RebroTestPackage                    int                  Test Package for prerelease versions.
2.0.0-g... RebroTestPackage                    int                  Test Package for prerelease versions.
2.0.0-b... RebroTestPackage                    int                  Test Package for prerelease versions.
1.0.0      RebroTestPackage                    int                  Test Package for prerelease versions.
1.0.0-o... RebroTestPackage                    int                  Test Package for prerelease versions.

**Comment by rebro-msft** [comment]
Thanks Manikyam, this has now been fixed:

```powershell
PS C:\WINDOWS\system32> Find-Module -Name TestPackage -Repository GalleryRolling -AllowPrerelease -AllVersions

Version              Name                                Repository           Description
-------              ----                                ----------           -----------
4.0.0-alpha9         TestPackage                         GalleryRolling       Module for DAC functionality
3.0.0                TestPackage                         GalleryRolling       Module for DAC functionality
2.0.0                TestPackage                         GalleryRolling       Module for DAC functionality
2.0.0-gamma300       TestPackage                         GalleryRolling       Module for DAC functionality
2.0.0-beta500        TestPackage                         GalleryRolling       Module for DAC functionality
1.0.0                TestPackage                         GalleryRolling       Module for DAC functionality
1.0.0-alpha001       TestPackage                         GalleryRolling       Module for DAC functionality
```
