### ISSUE TITLE
Wild cards are not supported when using -allowprerelease switch

### ISSUE THREAD

**Issue by raghushantha** [rebro-msft/psget-prerelease#4]
![image](https://user-images.githubusercontent.com/11727200/30610215-5d22af2c-9d32-11e7-9a2a-dfde8f0e7250.png)

**Comment by rebro-msft** [comment]
See https://github.com/PowerShell/PowerShellGet/issues/168 and https://github.com/rebro-msft/psget-prerelease/issues/6 for more information.  Closing this issue.
