### ISSUE TITLE
Find-Module RebroTest* -AllowPrerelease behavior

### ISSUE THREAD

**Issue by TylerLeonhardt** [rebro-msft/psget-prerelease#6]
During the bug bash, we discovered a bug in the prerelease code. The bug was that when you do:

`Find-Module RebroTest* -AllowPrerelease` nothing shows up in the output.

After talking to Mani, this should throw an error because the design says that wildcards are not allowed with `-AllowPrerelease` in `Find,Install,Update-Module`. 

However, consider this scenario:

A user publishes a new package (tyleonhaTestPackage) with only a prereleased version (1.0.0-alpha1 for example). No stable releases.
A user does `Find-Module` and this shows everything that isn't a prerelease (tyleonhaTestPackage doesn't show up).
A user does `Find-Module * -AllowPrerelease` and this throws an error by design (tyleonhaTestPackage doesn't show up).

This means that currently, by design, a preleased package that has no stable version will not show up in `Find-Module` unless you explicitly specify the full name of the package and of course `-AllowPrerelease`. No prerelease results will show up in `Find-Module` with a wildcard.

I propose that we allow the `-AllowPrerelease` flag to be used with wildcards in `Find-Module`

NOTE: I don't think we should allow this in `Install/Update-Module`... too much risk there but `Find-Module` is just a search and this should be supported so that you can find modules that are prerelease that have no stable versions.

The flow would be:
```
Find-Module tyleonhaTest* -AllowPrerelease
Install-Module tyleonhaTestModule -AllowPrerelease
```

**Comment by ghost** [comment]
Followed up with Mani, & this constraint is not specific to PreRelease, it's a limitation on use of wildcards when specifying version numbers. If you try "find-module azurerm* -version 3.3.1 -repository psgallery" you get an error. I would track this as a general issue, & evaluate it separate from the PreRelease rollout.

**Comment by TylerLeonhardt** [comment]
Opened in PSGet https://github.com/PowerShell/PowerShellGet/issues/168
